### ISSUE TITLE
> operator not merge strings into one line

### ISSUE THREAD

**Issue by ball6847** [rliebz/tusk#18]
I try to write a long command in multiline string with `>` operator and expecting it to merge my strings into one line ... with this behavior I don't have to worry about linebreaking in shell command.

But it has no difference between `|` and `>` , I still got line breaks.

```yml
tasks:
  composer:
    run: >
      docker run --rm -u ${UID}
        -e TERM=xterm-256color
        -v ${PWD}/server/app:/app
        -w /app
        --entrypoint "composer"
        million12/nginx-php:php70
        install 
```

Currently, I have to take care of line breaking myself even using > operator

```yml
tasks:
  composer:
    run: >
      docker run --rm -u ${UID} \
        -e TERM=xterm-256color \
        -v ${PWD}/server/app:/app \
        -w /app \
        --entrypoint "composer" \
        million12/nginx-php:php70 \
        install 
```

In case you might need it.
-------------

Go version ... I use gvm on ubuntu linux machine

```sh
$ go version
go version go1.9.2 linux/amd64
```
I installed tusk using the following command.

```sh
$ go get github.com/rliebz/tusk
```

Thanks

**Comment by rliebz** [comment]
Hi @ball6847 — thanks for the report.

From what I can tell, this is the intended parsing from [the yaml spec for folded style](http://yaml.org/spec/1.2/spec.html#id2796251). Specifically:
> Lines starting with white space characters (more-indented lines) are not folded.

You should be able to avoid using `\` by outdenting the trailing lines in the trailing lines of the shell command:
```yaml
tasks:
  composer:
    run: >
      docker run --rm -u ${UID}
      -e TERM=xterm-256color
      -v ${PWD}/server/app:/app
      -w /app
      --entrypoint "composer"
      million12/nginx-php:php70
      install 
```

**Comment by ball6847** [comment]
Thanks for the link, it works.  :smiley:
