### ISSUE TITLE
feature request: facilitate interactive (tty) tasks

### ISSUE THREAD

**Issue by automaticgiant** [rliebz/tusk#5]
maybe an option to exec if tusk doesn't want to mediate?

use case:
task to extract connection info from project (tf maybe) and ssh into a common target (node0/head, etc)

**Comment by rliebz** [comment]
Hey @automaticgiant, thanks for opening an issue.

If I'm understanding your use case correctly, you should be able to get the functionality you need with the `-q/--quiet` global flag.

For example, if you have some ssh task defined such as:

```yaml
tasks:
  ssh:
    run: gcloud compute ssh default
```

You can avoid all the stdout/stderr piping with:

```bash
$ tusk -q ssh
```

Looking at the documentation, that certainly isn't very clear, but does that solve for your use case?

**Comment by automaticgiant** [comment]
yes. i was misinterpreting what i was seeing. that does work. is there a supported way to specify in `tusk.yaml`?

**Comment by rliebz** [comment]
Right now there is not.

That being said, I'm not too happy with the idea of needing to pass a flag in order for interactivity to function, so I'll skip all the `=>` in the command output and allow that behavior by default.
