### ISSUE TITLE
trouble finding tusk.yml

### ISSUE THREAD

**Issue by automaticgiant** [rliebz/tusk#6]
haven't traced yet, or grokked https://github.com/rliebz/tusk/blob/2c310fcf22073e1c2109413b77a5af8a5f2baa80/config/file.go yet, so idk where it's looking, but i'm finding i have to specify `-f tusk.yml` in certain projects, even though it's in the working directory. 😕

**Comment by rliebz** [comment]
Basically, it starts from a call to `os.Getwd()`, joins that with `tusk.yml`, and repeats for each parent directory until it finds something or hits `/`.

Only thing I can think of is to make sure the file is named `tusk.yml` and not `tusk.yaml`, `Tusk.yml`, or any other variant. If you're in a symlinked directory or something like that, the more details you can send me about what your setup looks like, the better I can help support your use case, especially if you can help me reproduce this.

**Comment by automaticgiant** [comment]
Nailed it. i had a `tusk.yaml`
