### ISSUE TITLE
Only silence the Tusk output but not the output of exec/command/run

### ISSUE THREAD

**Issue by tstmrk** [rliebz/tusk#70]
Hi, all! First of thanks for this great tool!

I don't know if this is a feature already, but is it possible to disable the output of Tusk but not the output of the command?

Let's say I have this task:
```
  ls:
    run:
      exec: ls -la
```
The output is:
```
ls $ ls -la
total 16
drwxrwxrwx    2 root     root          4096 Mar 14 12:26 .
drwxrwxrwx    2 root     root          4096 Mar 14 12:22 ..
-rwxr-xr-x    1 root     root          4169 Mar 15 10:13 tusk.yml
```
I don't want the first line to be print, but I want the result of `exec` printed. When I use `-s` then nothing is shown.

The only thing I want is
```
total 16
drwxrwxrwx    2 root     root          4096 Mar 14 12:26 .
drwxrwxrwx    2 root     root          4096 Mar 14 12:22 ..
-rwxr-xr-x    1 root     root          4169 Mar 15 10:13 tusk.yml
```

**Comment by rliebz** [comment]
Hi @tstmrk, thanks for opening an issue.

The `-q`/`--quiet` flag should do what you're looking for. 

```
tusk -q ls
```

**Comment by tstmrk** [comment]
Aahh, whoops, sorry for not reading the help carefully! Thanks @rliebz !
