### ISSUE TITLE
Add tab completion command to gobal help output

### ISSUE THREAD

**Issue by airtonix** [rliebz/tusk#76]
**Is your feature request related to a problem? Please describe.**
Keep forgetting what the command for enabling tab completion is.

**Describe the solution you'd like**
add it to the output of `tusk --help`:
```sh

> tusk --help
...
Global Options:
   -f, --file <file>  Set file to use as the config file
   -h, --help         Show help and exit
   -q, --quiet        Only print command output and application errors
   -s, --silent       Print no output
   -V, --version      Print version and exit
   -v, --verbose      Print verbose output
   --install-completion [zsh|bash] Add tab completions to your shell profile/thing/magic/world

```

p.s. Love this tool.
![thankyou](https://github.com/jglovier/gifs/blob/gh-pages/thank-you/thank-you-zach.gif?raw=true)

**Comment by rliebz** [comment]
Released in [v0.6.1](https://github.com/rliebz/tusk/releases/tag/v0.6.1)!
