### ISSUE TITLE
make the program launch directory available as a variable

### ISSUE THREAD

**Issue by robinbryce** [rliebz/tusk#84]
**Is your feature request related to a problem? Please describe.**

I want to be able to pass relative paths in options and resolve them against the current working directory of the user when they invoke tusk. So I can do things like

    openssl --key ${launchdir}${userpath}

**Describe the solution you'd like**

A well known variable that I can reference using the existing syntax would be fine. Or a pointer to how to do this with current tusk

**Comment by robinbryce** [comment]
My current work around is to have a workdir option then invoke

tusk -f tusk.yml get -w $(pwd) mytask key.pem

Via an alias to take care of the -w bit

**Comment by rliebz** [comment]
The environment variables are evaluated before the working directory is changed, so you can actually capture the value of `$PWD` as an option. For example:

```yaml
tasks:
  pwd:
    options:
      dir:
        environment: PWD
    run: echo ${dir}
```

**Comment by robinbryce** [comment]
Ah, lovely. Thanks!
