### ISSUE TITLE
Load(source) environment variables from a file as configuration file.

### ISSUE THREAD

**Issue by elyoni** [rliebz/tusk#98]
Hello, and thank you. Your application is one of the best, and I use it every day for many of my projects. I'd like to suggest a new feature to load environment variables from a file. With this feature, we can use the same tusk.yml file for every project and only need to change the environment variables file.

The configuration file name will be specified at the top level of the tusk.yml file. Additionally, it can be optional; if the file exists, it will be loaded.

Thanks

**Comment by smyrman** [comment]
Potential workaround when the issue is ongoing.

What we do four our own tusk file, is that for tasks that needs it, we source the file through the shell:
```yaml
  run:
      - |
        set -e
        source ${resources}/docker-compose.gotest.env
```
This works if the env file is simple enough, but it does support comments with a `#` prefix..
